<?php

namespace App\Console\Commands;

use App\Models\User;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Hash;

/**
 * Emergency password reset for any user account.
 *
 * Usage:
 *   php artisan admin:reset-password admin@nalampulse.com
 *   php artisan admin:reset-password admin@nalampulse.com --password=MyNewPass123!
 *
 * If --password is omitted a strong random password is generated and printed.
 *
 * For Docker / self-hosted:
 *   docker exec -it <container> php artisan admin:reset-password admin@nalampulse.com
 */
class ResetAdminPassword extends Command
{
    protected $signature = 'admin:reset-password
                            {email : The email address of the account to reset}
                            {--password= : New password (omit to auto-generate)}';

    protected $description = 'Reset a user account password. Generates a strong random password if --password is not supplied.';

    public function handle(): int
    {
        $email = $this->argument('email');
        $user  = User::where('email', $email)->first();

        if (!$user) {
            $this->error("No user found with email: {$email}");
            $this->line('');
            $this->line('To list all users:');
            $this->line('  php artisan tinker --execute="App\Models\User::all([\'id\',\'email\',\'role\'])->each(fn(\$u)=>print(\$u->email.\' (\'.\$u->role.\')\'.PHP_EOL));"');
            return self::FAILURE;
        }

        $password      = $this->option('password');
        $autoGenerated = false;

        if (empty($password)) {
            $password      = $this->generatePassword();
            $autoGenerated = true;
        }

        if (strlen($password) < 8) {
            $this->error('Password must be at least 8 characters.');
            return self::FAILURE;
        }

        $user->password = Hash::make($password);
        $user->save();

        // Also invalidate any pending password-reset tokens for this user
        \Illuminate\Support\Facades\DB::table('password_reset_tokens')
            ->where('email', $email)
            ->delete();

        $line = str_repeat('─', 55);
        $this->line('');
        $this->line($line);
        $this->info('  Password reset successful');
        $this->line($line);
        $this->line("  Account : {$email}  ({$user->role})");
        $this->line("  Password: {$password}");
        if ($autoGenerated) {
            $this->line('  (auto-generated — copy it now, it will not be shown again)');
        }
        $this->line($line);
        $this->line('');

        return self::SUCCESS;
    }

    private function generatePassword(): string
    {
        $upper   = 'ABCDEFGHJKLMNPQRSTUVWXYZ';
        $lower   = 'abcdefghjkmnpqrstuvwxyz';
        $digits  = '23456789';
        $symbols = '!@#$%^&*-_+=?';

        $password  = '';
        $password .= $upper[random_int(0, strlen($upper) - 1)];
        $password .= $upper[random_int(0, strlen($upper) - 1)];
        $password .= $lower[random_int(0, strlen($lower) - 1)];
        $password .= $lower[random_int(0, strlen($lower) - 1)];
        $password .= $digits[random_int(0, strlen($digits) - 1)];
        $password .= $digits[random_int(0, strlen($digits) - 1)];
        $password .= $symbols[random_int(0, strlen($symbols) - 1)];

        $all = $upper . $lower . $digits . $symbols;
        while (strlen($password) < 20) {
            $password .= $all[random_int(0, strlen($all) - 1)];
        }

        return str_shuffle($password);
    }
}
