<?php

namespace Database\Seeders;

use App\Models\Organization;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

/**
 * Clean-slate seeder for production / Docker deployments.
 *
 * Creates only the platform super-admin account.
 * No demo data, no test users, no sample organizations.
 *
 * Reads from environment variables:
 *   ADMIN_EMAIL    — super-admin login email   (default: admin@nalampulse.com)
 *   ADMIN_PASSWORD — super-admin password      (default: auto-generated, printed to log)
 */
class ProductionSeeder extends Seeder
{
    public function run(): void
    {
        $email    = env('ADMIN_EMAIL', 'admin@nalampulse.com');
        $password = env('ADMIN_PASSWORD');

        $autoGenerated = false;
        if (empty($password)) {
            // Generate a strong 20-character password: uppercase + lowercase + digits + symbols
            $password      = $this->generatePassword();
            $autoGenerated = true;
        }

        User::updateOrCreate(
            ['email' => $email],
            [
                'name'            => 'Platform Admin',
                'email'           => $email,
                'password'        => $password,
                'role'            => 'super_admin',
                'organization_id' => null,
                'is_active'       => true,
            ]
        );

        if ($autoGenerated) {
            // Print to stdout so it appears in `docker logs` on first boot
            $line = str_repeat('=', 60);
            $this->command->line('');
            $this->command->line($line);
            $this->command->line('  SUPER ADMIN CREDENTIALS (save these now)');
            $this->command->line($line);
            $this->command->line("  Email   : {$email}");
            $this->command->line("  Password: {$password}");
            $this->command->line($line);
            $this->command->line('  You can change this password in Settings after logging in.');
            $this->command->line('  To recover access, run:');
            $this->command->line('    php artisan admin:reset-password ' . $email);
            $this->command->line($line);
            $this->command->line('');
        } else {
            $this->command->info("Super admin created: {$email}");
        }
    }

    private function generatePassword(): string
    {
        $upper   = 'ABCDEFGHJKLMNPQRSTUVWXYZ';   // no I/O (confusing)
        $lower   = 'abcdefghjkmnpqrstuvwxyz';     // no l (confusing)
        $digits  = '23456789';                      // no 0/1 (confusing)
        $symbols = '!@#$%^&*-_+=?';

        $password  = '';
        $password .= $upper[random_int(0, strlen($upper) - 1)];
        $password .= $upper[random_int(0, strlen($upper) - 1)];
        $password .= $lower[random_int(0, strlen($lower) - 1)];
        $password .= $lower[random_int(0, strlen($lower) - 1)];
        $password .= $digits[random_int(0, strlen($digits) - 1)];
        $password .= $digits[random_int(0, strlen($digits) - 1)];
        $password .= $symbols[random_int(0, strlen($symbols) - 1)];

        // Fill remaining chars from all pools combined
        $all = $upper . $lower . $digits . $symbols;
        while (strlen($password) < 20) {
            $password .= $all[random_int(0, strlen($all) - 1)];
        }

        // Shuffle so the guaranteed chars aren't always at the front
        return str_shuffle($password);
    }
}
