<?php

namespace App\Services;

use App\Models\Organization;

class ThemeService
{
    public static function palettes(): array
    {
        return [
            'indigo_night' => [
                'name' => 'Indigo Night',
                'sidebar_style' => 'dark',
                'colors' => [
                    '--primary' => '#4f46e5',
                    '--primary-hover' => '#4338ca',
                    '--primary-light' => '#eef2ff',
                    '--primary-50' => '#eef2ff',
                    '--primary-100' => '#e0e7ff',
                    '--primary-200' => '#c7d2fe',
                    '--primary-500' => '#6366f1',
                    '--primary-600' => '#4f46e5',
                    '--primary-700' => '#4338ca',
                    '--primary-800' => '#3730a3',
                    '--sidebar-bg' => '#0f172a',
                    '--sidebar-border' => 'rgba(255,255,255,0.06)',
                    '--sidebar-text' => '#94a3b8',
                    '--sidebar-text-hover' => '#e2e8f0',
                    '--sidebar-active-bg' => 'rgba(99,102,241,0.12)',
                    '--sidebar-active-text' => '#a5b4fc',
                    '--sidebar-heading' => '#475569',
                    '--sidebar-link-hover-bg' => 'rgba(255,255,255,0.06)',
                    '--sidebar-user-name-color' => '#e2e8f0',
                    '--shadow-ring' => '0 0 0 3px rgba(79,70,229,0.15)',
                    '--primary-shadow' => 'rgba(79,70,229,0.3)',
                    '--brand-gradient-from' => '#6366f1',
                    '--brand-gradient-to' => '#8b5cf6',
                    '--brand-text-accent' => '#a5b4fc',
                    '--auth-bg-from' => '#0f172a',
                    '--auth-bg-mid' => '#1e1b4b',
                    '--auth-bg-to' => '#312e81',
                ],
            ],
            'ocean_breeze' => [
                'name' => 'Ocean Breeze',
                'sidebar_style' => 'dark',
                'colors' => [
                    '--primary' => '#0284c7',
                    '--primary-hover' => '#0369a1',
                    '--primary-light' => '#f0f9ff',
                    '--primary-50' => '#f0f9ff',
                    '--primary-100' => '#e0f2fe',
                    '--primary-200' => '#bae6fd',
                    '--primary-500' => '#0ea5e9',
                    '--primary-600' => '#0284c7',
                    '--primary-700' => '#0369a1',
                    '--primary-800' => '#075985',
                    '--sidebar-bg' => '#0c4a6e',
                    '--sidebar-border' => 'rgba(255,255,255,0.08)',
                    '--sidebar-text' => '#bae6fd',
                    '--sidebar-text-hover' => '#f0f9ff',
                    '--sidebar-active-bg' => 'rgba(14,165,233,0.15)',
                    '--sidebar-active-text' => '#7dd3fc',
                    '--sidebar-heading' => '#7dd3fc',
                    '--sidebar-link-hover-bg' => 'rgba(255,255,255,0.07)',
                    '--sidebar-user-name-color' => '#e0f2fe',
                    '--shadow-ring' => '0 0 0 3px rgba(2,132,199,0.15)',
                    '--primary-shadow' => 'rgba(2,132,199,0.3)',
                    '--brand-gradient-from' => '#0ea5e9',
                    '--brand-gradient-to' => '#06b6d4',
                    '--brand-text-accent' => '#7dd3fc',
                    '--auth-bg-from' => '#0c4a6e',
                    '--auth-bg-mid' => '#075985',
                    '--auth-bg-to' => '#0369a1',
                ],
            ],
            'emerald_forest' => [
                'name' => 'Emerald Forest',
                'sidebar_style' => 'dark',
                'colors' => [
                    '--primary' => '#059669',
                    '--primary-hover' => '#047857',
                    '--primary-light' => '#ecfdf5',
                    '--primary-50' => '#ecfdf5',
                    '--primary-100' => '#d1fae5',
                    '--primary-200' => '#a7f3d0',
                    '--primary-500' => '#10b981',
                    '--primary-600' => '#059669',
                    '--primary-700' => '#047857',
                    '--primary-800' => '#065f46',
                    '--sidebar-bg' => '#064e3b',
                    '--sidebar-border' => 'rgba(255,255,255,0.08)',
                    '--sidebar-text' => '#a7f3d0',
                    '--sidebar-text-hover' => '#ecfdf5',
                    '--sidebar-active-bg' => 'rgba(16,185,129,0.15)',
                    '--sidebar-active-text' => '#6ee7b7',
                    '--sidebar-heading' => '#6ee7b7',
                    '--sidebar-link-hover-bg' => 'rgba(255,255,255,0.07)',
                    '--sidebar-user-name-color' => '#d1fae5',
                    '--shadow-ring' => '0 0 0 3px rgba(5,150,105,0.15)',
                    '--primary-shadow' => 'rgba(5,150,105,0.3)',
                    '--brand-gradient-from' => '#10b981',
                    '--brand-gradient-to' => '#14b8a6',
                    '--brand-text-accent' => '#6ee7b7',
                    '--auth-bg-from' => '#064e3b',
                    '--auth-bg-mid' => '#065f46',
                    '--auth-bg-to' => '#047857',
                ],
            ],
            'sunset_ember' => [
                'name' => 'Sunset Ember',
                'sidebar_style' => 'dark',
                'colors' => [
                    '--primary' => '#ea580c',
                    '--primary-hover' => '#c2410c',
                    '--primary-light' => '#fff7ed',
                    '--primary-50' => '#fff7ed',
                    '--primary-100' => '#ffedd5',
                    '--primary-200' => '#fed7aa',
                    '--primary-500' => '#f97316',
                    '--primary-600' => '#ea580c',
                    '--primary-700' => '#c2410c',
                    '--primary-800' => '#9a3412',
                    '--sidebar-bg' => '#1c1917',
                    '--sidebar-border' => 'rgba(255,255,255,0.06)',
                    '--sidebar-text' => '#a8a29e',
                    '--sidebar-text-hover' => '#e7e5e4',
                    '--sidebar-active-bg' => 'rgba(249,115,22,0.12)',
                    '--sidebar-active-text' => '#fdba74',
                    '--sidebar-heading' => '#78716c',
                    '--sidebar-link-hover-bg' => 'rgba(255,255,255,0.06)',
                    '--sidebar-user-name-color' => '#e7e5e4',
                    '--shadow-ring' => '0 0 0 3px rgba(234,88,12,0.15)',
                    '--primary-shadow' => 'rgba(234,88,12,0.3)',
                    '--brand-gradient-from' => '#f97316',
                    '--brand-gradient-to' => '#f59e0b',
                    '--brand-text-accent' => '#fdba74',
                    '--auth-bg-from' => '#1c1917',
                    '--auth-bg-mid' => '#44403c',
                    '--auth-bg-to' => '#78716c',
                ],
            ],
            'crimson_rose' => [
                'name' => 'Crimson Rose',
                'sidebar_style' => 'dark',
                'colors' => [
                    '--primary' => '#e11d48',
                    '--primary-hover' => '#be123c',
                    '--primary-light' => '#fff1f2',
                    '--primary-50' => '#fff1f2',
                    '--primary-100' => '#ffe4e6',
                    '--primary-200' => '#fecdd3',
                    '--primary-500' => '#f43f5e',
                    '--primary-600' => '#e11d48',
                    '--primary-700' => '#be123c',
                    '--primary-800' => '#9f1239',
                    '--sidebar-bg' => '#1a1a2e',
                    '--sidebar-border' => 'rgba(255,255,255,0.06)',
                    '--sidebar-text' => '#a1a1aa',
                    '--sidebar-text-hover' => '#e4e4e7',
                    '--sidebar-active-bg' => 'rgba(244,63,94,0.12)',
                    '--sidebar-active-text' => '#fda4af',
                    '--sidebar-heading' => '#71717a',
                    '--sidebar-link-hover-bg' => 'rgba(255,255,255,0.06)',
                    '--sidebar-user-name-color' => '#e4e4e7',
                    '--shadow-ring' => '0 0 0 3px rgba(225,29,72,0.15)',
                    '--primary-shadow' => 'rgba(225,29,72,0.3)',
                    '--brand-gradient-from' => '#f43f5e',
                    '--brand-gradient-to' => '#ec4899',
                    '--brand-text-accent' => '#fda4af',
                    '--auth-bg-from' => '#1a1a2e',
                    '--auth-bg-mid' => '#4c1d45',
                    '--auth-bg-to' => '#831843',
                ],
            ],
            'royal_purple' => [
                'name' => 'Royal Purple',
                'sidebar_style' => 'dark',
                'colors' => [
                    '--primary' => '#7c3aed',
                    '--primary-hover' => '#6d28d9',
                    '--primary-light' => '#f5f3ff',
                    '--primary-50' => '#f5f3ff',
                    '--primary-100' => '#ede9fe',
                    '--primary-200' => '#ddd6fe',
                    '--primary-500' => '#8b5cf6',
                    '--primary-600' => '#7c3aed',
                    '--primary-700' => '#6d28d9',
                    '--primary-800' => '#5b21b6',
                    '--sidebar-bg' => '#1e1b4b',
                    '--sidebar-border' => 'rgba(255,255,255,0.06)',
                    '--sidebar-text' => '#a5b4fc',
                    '--sidebar-text-hover' => '#e0e7ff',
                    '--sidebar-active-bg' => 'rgba(139,92,246,0.15)',
                    '--sidebar-active-text' => '#c4b5fd',
                    '--sidebar-heading' => '#6366f1',
                    '--sidebar-link-hover-bg' => 'rgba(255,255,255,0.06)',
                    '--sidebar-user-name-color' => '#e0e7ff',
                    '--shadow-ring' => '0 0 0 3px rgba(124,58,237,0.15)',
                    '--primary-shadow' => 'rgba(124,58,237,0.3)',
                    '--brand-gradient-from' => '#8b5cf6',
                    '--brand-gradient-to' => '#a78bfa',
                    '--brand-text-accent' => '#c4b5fd',
                    '--auth-bg-from' => '#1e1b4b',
                    '--auth-bg-mid' => '#312e81',
                    '--auth-bg-to' => '#5b21b6',
                ],
            ],
            'teal_horizon' => [
                'name' => 'Teal Horizon',
                'sidebar_style' => 'light',
                'colors' => [
                    '--primary' => '#0d9488',
                    '--primary-hover' => '#0f766e',
                    '--primary-light' => '#f0fdfa',
                    '--primary-50' => '#f0fdfa',
                    '--primary-100' => '#ccfbf1',
                    '--primary-200' => '#99f6e4',
                    '--primary-500' => '#14b8a6',
                    '--primary-600' => '#0d9488',
                    '--primary-700' => '#0f766e',
                    '--primary-800' => '#115e59',
                    '--sidebar-bg' => '#ffffff',
                    '--sidebar-border' => '#e5e7eb',
                    '--sidebar-text' => '#4b5563',
                    '--sidebar-text-hover' => '#111827',
                    '--sidebar-active-bg' => '#f0fdfa',
                    '--sidebar-active-text' => '#0d9488',
                    '--sidebar-heading' => '#9ca3af',
                    '--sidebar-link-hover-bg' => '#f3f4f6',
                    '--sidebar-user-name-color' => '#111827',
                    '--shadow-ring' => '0 0 0 3px rgba(13,148,136,0.15)',
                    '--primary-shadow' => 'rgba(13,148,136,0.3)',
                    '--brand-gradient-from' => '#14b8a6',
                    '--brand-gradient-to' => '#06b6d4',
                    '--brand-text-accent' => '#0d9488',
                    '--auth-bg-from' => '#115e59',
                    '--auth-bg-mid' => '#0f766e',
                    '--auth-bg-to' => '#0d9488',
                ],
            ],
            'slate_professional' => [
                'name' => 'Slate Professional',
                'sidebar_style' => 'light',
                'colors' => [
                    '--primary' => '#475569',
                    '--primary-hover' => '#334155',
                    '--primary-light' => '#f8fafc',
                    '--primary-50' => '#f8fafc',
                    '--primary-100' => '#f1f5f9',
                    '--primary-200' => '#e2e8f0',
                    '--primary-500' => '#64748b',
                    '--primary-600' => '#475569',
                    '--primary-700' => '#334155',
                    '--primary-800' => '#1e293b',
                    '--sidebar-bg' => '#f8fafc',
                    '--sidebar-border' => '#e2e8f0',
                    '--sidebar-text' => '#475569',
                    '--sidebar-text-hover' => '#0f172a',
                    '--sidebar-active-bg' => '#e2e8f0',
                    '--sidebar-active-text' => '#1e293b',
                    '--sidebar-heading' => '#94a3b8',
                    '--sidebar-link-hover-bg' => '#f1f5f9',
                    '--sidebar-user-name-color' => '#1e293b',
                    '--shadow-ring' => '0 0 0 3px rgba(71,85,105,0.15)',
                    '--primary-shadow' => 'rgba(71,85,105,0.3)',
                    '--brand-gradient-from' => '#475569',
                    '--brand-gradient-to' => '#64748b',
                    '--brand-text-accent' => '#475569',
                    '--auth-bg-from' => '#0f172a',
                    '--auth-bg-mid' => '#1e293b',
                    '--auth-bg-to' => '#334155',
                ],
            ],
            'amber_warmth' => [
                'name' => 'Amber Warmth',
                'sidebar_style' => 'light',
                'colors' => [
                    '--primary' => '#d97706',
                    '--primary-hover' => '#b45309',
                    '--primary-light' => '#fffbeb',
                    '--primary-50' => '#fffbeb',
                    '--primary-100' => '#fef3c7',
                    '--primary-200' => '#fde68a',
                    '--primary-500' => '#f59e0b',
                    '--primary-600' => '#d97706',
                    '--primary-700' => '#b45309',
                    '--primary-800' => '#92400e',
                    '--sidebar-bg' => '#fffbeb',
                    '--sidebar-border' => '#fde68a',
                    '--sidebar-text' => '#78716c',
                    '--sidebar-text-hover' => '#1c1917',
                    '--sidebar-active-bg' => '#fef3c7',
                    '--sidebar-active-text' => '#92400e',
                    '--sidebar-heading' => '#a8a29e',
                    '--sidebar-link-hover-bg' => '#fef3c7',
                    '--sidebar-user-name-color' => '#1c1917',
                    '--shadow-ring' => '0 0 0 3px rgba(217,119,6,0.15)',
                    '--primary-shadow' => 'rgba(217,119,6,0.3)',
                    '--brand-gradient-from' => '#f59e0b',
                    '--brand-gradient-to' => '#f97316',
                    '--brand-text-accent' => '#b45309',
                    '--auth-bg-from' => '#78350f',
                    '--auth-bg-mid' => '#92400e',
                    '--auth-bg-to' => '#b45309',
                ],
            ],
            'midnight_blue' => [
                'name' => 'Midnight Blue',
                'sidebar_style' => 'dark',
                'colors' => [
                    '--primary' => '#2563eb',
                    '--primary-hover' => '#1d4ed8',
                    '--primary-light' => '#eff6ff',
                    '--primary-50' => '#eff6ff',
                    '--primary-100' => '#dbeafe',
                    '--primary-200' => '#bfdbfe',
                    '--primary-500' => '#3b82f6',
                    '--primary-600' => '#2563eb',
                    '--primary-700' => '#1d4ed8',
                    '--primary-800' => '#1e40af',
                    '--sidebar-bg' => '#111827',
                    '--sidebar-border' => 'rgba(255,255,255,0.06)',
                    '--sidebar-text' => '#9ca3af',
                    '--sidebar-text-hover' => '#f3f4f6',
                    '--sidebar-active-bg' => 'rgba(59,130,246,0.12)',
                    '--sidebar-active-text' => '#93c5fd',
                    '--sidebar-heading' => '#6b7280',
                    '--sidebar-link-hover-bg' => 'rgba(255,255,255,0.06)',
                    '--sidebar-user-name-color' => '#f3f4f6',
                    '--shadow-ring' => '0 0 0 3px rgba(37,99,235,0.15)',
                    '--primary-shadow' => 'rgba(37,99,235,0.3)',
                    '--brand-gradient-from' => '#3b82f6',
                    '--brand-gradient-to' => '#6366f1',
                    '--brand-text-accent' => '#93c5fd',
                    '--auth-bg-from' => '#111827',
                    '--auth-bg-mid' => '#1e3a5f',
                    '--auth-bg-to' => '#1e40af',
                ],
            ],
        ];
    }

    public static function getThemeKey(?Organization $org): string
    {
        if (!$org) {
            return 'indigo_night';
        }
        $settings = $org->settings ?? [];
        $key = $settings['theme'] ?? 'indigo_night';

        return array_key_exists($key, static::palettes()) ? $key : 'indigo_night';
    }

    public static function resolve(?Organization $org): array
    {
        $key = static::getThemeKey($org);
        return static::palettes()[$key];
    }

    public static function cssOverrides(?Organization $org): string
    {
        $key = static::getThemeKey($org);
        if ($key === 'indigo_night') {
            return '';
        }

        $palette = static::palettes()[$key];
        $lines = [':root {'];
        foreach ($palette['colors'] as $var => $value) {
            $lines[] = "    {$var}: {$value};";
        }
        $lines[] = '}';

        return '<style id="theme-overrides">' . "\n" . implode("\n", $lines) . "\n" . '</style>';
    }
}
