#!/bin/bash
# =============================================================================
# Nalam Pulse — Sync localhost DB to demo dump
#
# Run from the project root (Git Bash on Windows) to export your local
# talent_db data into a SQL file used by the GCP installer for demo mode.
#
# Usage:
#   bash deploy/gcp/sync-demo-db.sh
#
# The dump is DATA ONLY (no CREATE TABLE). The Docker entrypoint runs
# migrations first to create tables, then the installer imports this data.
#
# After running, commit + push:
#   git add deploy/gcp/demo-data.sql
#   git commit -m "Sync demo data from localhost"
#   git push
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DUMP_FILE="$SCRIPT_DIR/demo-data.sql"
MYSQL="/c/xampp/mysql/bin/mysql.exe"
MYSQLDUMP="/c/xampp/mysql/bin/mysqldump.exe"
DB_NAME="talent_db"
DB_USER="root"

echo "=== Nalam Pulse — Demo Data Sync ==="
echo ""

# Verify mysql is accessible
if ! "$MYSQL" -u "$DB_USER" -e "SELECT 1" &>/dev/null; then
    echo "ERROR: Cannot connect to MySQL. Make sure XAMPP MySQL is running."
    exit 1
fi

# Tables to skip entirely (ephemeral data)
SKIP_TABLES=(
    "sessions"
    "cache"
    "cache_locks"
    "jobs"
    "failed_jobs"
    "job_batches"
    "password_reset_tokens"
    "migrations"
    "activity_logs"
)

# Build --ignore-table flags
IGNORE_FLAGS=""
for t in "${SKIP_TABLES[@]}"; do
    IGNORE_FLAGS="$IGNORE_FLAGS --ignore-table=${DB_NAME}.${t}"
done

echo "[1/2] Dumping data (no table structure, no ephemeral tables)..."

# Header
cat > "$DUMP_FILE" <<'HEADER'
-- =============================================================================
-- Nalam Pulse — Demo Data Dump
-- Generated by: deploy/gcp/sync-demo-db.sh
-- Import AFTER migrations have run (tables already exist).
-- =============================================================================
SET FOREIGN_KEY_CHECKS=0;
SET UNIQUE_CHECKS=0;
SET AUTOCOMMIT=0;

HEADER

# Data-only dump with INSERT statements
"$MYSQLDUMP" -u "$DB_USER" \
    --no-create-info \
    --skip-comments \
    --compact \
    --complete-insert \
    --skip-triggers \
    $IGNORE_FLAGS \
    "$DB_NAME" >> "$DUMP_FILE"

# Footer
cat >> "$DUMP_FILE" <<'FOOTER'

SET FOREIGN_KEY_CHECKS=1;
SET UNIQUE_CHECKS=1;
COMMIT;
SET AUTOCOMMIT=1;
FOOTER

echo "[2/3] Compressing..."
gzip -f "$DUMP_FILE"
GZ_FILE="${DUMP_FILE}.gz"

echo "[3/3] Done!"
echo ""

SIZE=$(du -h "$GZ_FILE" | cut -f1)
echo "  File: $GZ_FILE"
echo "  Size: $SIZE (compressed)"
echo ""

# Show data summary
echo "  Data included:"
"$MYSQL" -u "$DB_USER" -e "
    SELECT table_name AS 'Table', table_rows AS 'Rows'
    FROM information_schema.tables
    WHERE table_schema='$DB_NAME' AND table_rows > 0
    ORDER BY table_rows DESC;
" 2>/dev/null

echo ""
echo "  Next steps:"
echo "    git add deploy/gcp/demo-data.sql.gz"
echo "    git commit -m 'Sync demo data from localhost'"
echo "    git push"
